// AUTO-GENERATED by hono-aep-drizzle from the AEP resource definitions.
// Do not edit by hand — regenerate with your db:schema script.
// Extend in a wrapper module (e.g. schema.ts re-exporting this file).
import { index, sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";

export const projects = sqliteTable("projects", {
  id: text("id").primaryKey(),
  display_name: text("display_name").notNull(),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
});

export const forms = sqliteTable("forms", {
  id: text("id").primaryKey(),
  project_id: text("project_id").notNull().references(() => projects.id),
  display_name: text("display_name").notNull(),
  notify_email: text("notify_email").notNull(),
  redirect_url: text("redirect_url"),
  submit_key: text("submit_key"),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
});

export const submissions = sqliteTable("submissions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  form_id: text("form_id").notNull().references(() => forms.id),
  data: text("data", { mode: "json" }).notNull(),
  replyto: text("replyto"),
  verdict: text("verdict", { enum: ["ham", "spam", "unverified"] }),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
});

export const collections = sqliteTable("collections", {
  id: text("id").primaryKey(),
  project_id: text("project_id").notNull().references(() => projects.id),
  definition: text("definition", { mode: "json" }).notNull(),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
});

export const themes = sqliteTable("themes", {
  id: text("id").primaryKey(),
  project_id: text("project_id").notNull().references(() => projects.id),
  css: text("css").notNull(),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
});

export const pages = sqliteTable("pages", {
  id: text("id").primaryKey(),
  project_id: text("project_id").notNull().references(() => projects.id),
  title: text("title").notNull(),
  data: text("data", { mode: "json" }).notNull(),
  seo: text("seo", { mode: "json" }),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
});

export const blocks = sqliteTable("blocks", {
  id: text("id").primaryKey(),
  project_id: text("project_id").notNull().references(() => projects.id),
  title: text("title"),
  data: text("data", { mode: "json" }).notNull(),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
});

/** Tables keyed by resource singular — pass to drizzleAepStorage(). */
export const tables = {
  "project": projects,
  "form": forms,
  "submission": submissions,
  "collection": collections,
  "theme": themes,
  "page": pages,
  "block": blocks,
} as const;
