// AUTO-GENERATED by hono-aep-drizzle from the AEP resource definitions.
// Do not edit by hand — regenerate with your db:schema script.
// Extend in a wrapper module (e.g. schema.ts re-exporting this file).
import { index, primaryKey, sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";

export const projects = sqliteTable("projects", {
  id: text("id").primaryKey(),
  display_name: text("display_name").notNull(),
  auth_pool: text("auth_pool", { mode: "json" }),
  site: text("site", { mode: "json" }),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
});

export const forms = sqliteTable("forms", {
  id: text("id").notNull(),
  project_id: text("project_id").notNull().references(() => projects.id),
  display_name: text("display_name").notNull(),
  notify_email: text("notify_email").notNull(),
  redirect_url: text("redirect_url"),
  submit_key: text("submit_key"),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
}, (table) => [primaryKey({ columns: [table.project_id, table.id] })]);

export const submissions = sqliteTable("submissions", {
  id: integer("id").notNull(),
  form_id: text("form_id").notNull().references(() => forms.id),
  data: text("data", { mode: "json" }).notNull(),
  replyto: text("replyto"),
  verdict: text("verdict", { enum: ["ham", "spam", "unverified"] }),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
}, (table) => [primaryKey({ columns: [table.form_id, table.id] })]);

export const collections = sqliteTable("collections", {
  id: text("id").notNull(),
  project_id: text("project_id").notNull().references(() => projects.id),
  definition: text("definition", { mode: "json" }).notNull(),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
}, (table) => [primaryKey({ columns: [table.project_id, table.id] })]);

export const domains = sqliteTable("domains", {
  id: text("id").notNull(),
  project_id: text("project_id").notNull().references(() => projects.id),
  kind: text("kind", { enum: ["api", "site"] }).notNull(),
  challenge: text("challenge"),
  verified_time: text("verified_time"),
  last_error: text("last_error"),
  created_by: text("created_by"),
  state: text("state", { enum: ["PENDING", "ACTIVE", "FAILED"] }).notNull(),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
}, (table) => [primaryKey({ columns: [table.project_id, table.id] })]);

export const kinds = sqliteTable("kinds", {
  id: text("id").notNull(),
  project_id: text("project_id").notNull().references(() => projects.id),
  definition: text("definition", { mode: "json" }).notNull(),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
}, (table) => [primaryKey({ columns: [table.project_id, table.id] })]);

export const themes = sqliteTable("themes", {
  id: text("id").notNull(),
  project_id: text("project_id").notNull().references(() => projects.id),
  css: text("css").notNull(),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
}, (table) => [primaryKey({ columns: [table.project_id, table.id] })]);

export const pages = sqliteTable("pages", {
  id: text("id").notNull(),
  project_id: text("project_id").notNull().references(() => projects.id),
  title: text("title").notNull(),
  data: text("data", { mode: "json" }).notNull(),
  seo: text("seo", { mode: "json" }),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
}, (table) => [primaryKey({ columns: [table.project_id, table.id] })]);

export const blocks = sqliteTable("blocks", {
  id: text("id").notNull(),
  project_id: text("project_id").notNull().references(() => projects.id),
  title: text("title"),
  data: text("data", { mode: "json" }).notNull(),
  created_by: text("created_by"),
  create_time: text("create_time").notNull(),
  update_time: text("update_time").notNull(),
}, (table) => [primaryKey({ columns: [table.project_id, table.id] })]);

/** Tables keyed by resource singular — pass to drizzleAepStorage(). */
export const tables = {
  "project": projects,
  "form": forms,
  "submission": submissions,
  "collection": collections,
  "domain": domains,
  "kind": kinds,
  "theme": themes,
  "page": pages,
  "block": blocks,
} as const;
