/**
 * Snapshot hono-aep-bootstrap-ui's source into a generated TS module so
 * the Worker can SERVE it (no fs at the edge): the hosted admin.html
 * imports /v1/projects/{p}/site/bootstrap-ui.js. Re-run after editing
 * the package (build-studio.ts runs it as part of the deploy ritual).
 */
const source = await Bun.file(
  new URL("../../customPackages/hono-aep-bootstrap-ui/src/index.js", import.meta.url),
).text();
const out = `// GENERATED by scripts/vendor-bootstrap-ui.ts — do not edit.
// Source of truth: customPackages/hono-aep-bootstrap-ui/src/index.js
export const bootstrapUiSource = ${JSON.stringify(source)};
`;
await Bun.write(new URL("../src/server/generated/bootstrap-ui-source.ts", import.meta.url), out);
console.log(`vendored bootstrap-ui (${source.length} chars) → src/server/generated/`);
